/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BallotInterface extends ethers.utils.Interface {
  functions: {
    "chairperson()": FunctionFragment;
    "delegate(address)": FunctionFragment;
    "getProposal()": FunctionFragment;
    "getProposalLength()": FunctionFragment;
    "getVotersList()": FunctionFragment;
    "giveRightToVote(address)": FunctionFragment;
    "proposals(uint256)": FunctionFragment;
    "title()": FunctionFragment;
    "vote(uint256)": FunctionFragment;
    "voters(address)": FunctionFragment;
    "votersList(uint256)": FunctionFragment;
    "winnerName()": FunctionFragment;
    "winningProposal()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "chairperson",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "delegate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVotersList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "giveRightToVote",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "voters", values: [string]): string;
  encodeFunctionData(
    functionFragment: "votersList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winnerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winningProposal",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "chairperson",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotersList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "giveRightToVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votersList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winnerName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningProposal",
    data: BytesLike
  ): Result;

  events: {
    "Voted(address)": EventFragment;
    "VoterJoin(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Voted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoterJoin"): EventFragment;
}

export type VotedEvent = TypedEvent<[string] & { voter: string }>;

export type VoterJoinEvent = TypedEvent<
  [string, string] & { chairperson: string; voter: string }
>;

export class Ballot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BallotInterface;

  functions: {
    chairperson(overrides?: CallOverrides): Promise<[string]>;

    delegate(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getProposal(
      overrides?: CallOverrides
    ): Promise<
      [([string, BigNumber] & { name: string; voteCount: BigNumber })[]]
    >;

    getProposalLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVotersList(overrides?: CallOverrides): Promise<[string[]]>;

    giveRightToVote(
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

    title(overrides?: CallOverrides): Promise<[string]>;

    vote(
      proposal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, string, BigNumber] & {
        weight: BigNumber;
        voted: boolean;
        delegate: string;
        vote: BigNumber;
      }
    >;

    votersList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    winnerName(
      overrides?: CallOverrides
    ): Promise<[string] & { winnerName_: string }>;

    winningProposal(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { winningProposal_: BigNumber }>;
  };

  chairperson(overrides?: CallOverrides): Promise<string>;

  delegate(
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getProposal(
    overrides?: CallOverrides
  ): Promise<([string, BigNumber] & { name: string; voteCount: BigNumber })[]>;

  getProposalLength(overrides?: CallOverrides): Promise<BigNumber>;

  getVotersList(overrides?: CallOverrides): Promise<string[]>;

  giveRightToVote(
    voter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposals(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

  title(overrides?: CallOverrides): Promise<string>;

  vote(
    proposal: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voters(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean, string, BigNumber] & {
      weight: BigNumber;
      voted: boolean;
      delegate: string;
      vote: BigNumber;
    }
  >;

  votersList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  winnerName(overrides?: CallOverrides): Promise<string>;

  winningProposal(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    chairperson(overrides?: CallOverrides): Promise<string>;

    delegate(to: string, overrides?: CallOverrides): Promise<void>;

    getProposal(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber] & { name: string; voteCount: BigNumber })[]
    >;

    getProposalLength(overrides?: CallOverrides): Promise<BigNumber>;

    getVotersList(overrides?: CallOverrides): Promise<string[]>;

    giveRightToVote(voter: string, overrides?: CallOverrides): Promise<void>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

    title(overrides?: CallOverrides): Promise<string>;

    vote(proposal: BigNumberish, overrides?: CallOverrides): Promise<void>;

    voters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, string, BigNumber] & {
        weight: BigNumber;
        voted: boolean;
        delegate: string;
        vote: BigNumber;
      }
    >;

    votersList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    winnerName(overrides?: CallOverrides): Promise<string>;

    winningProposal(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Voted(address)"(
      voter?: null
    ): TypedEventFilter<[string], { voter: string }>;

    Voted(voter?: null): TypedEventFilter<[string], { voter: string }>;

    "VoterJoin(address,address)"(
      chairperson?: string | null,
      voter?: null
    ): TypedEventFilter<
      [string, string],
      { chairperson: string; voter: string }
    >;

    VoterJoin(
      chairperson?: string | null,
      voter?: null
    ): TypedEventFilter<
      [string, string],
      { chairperson: string; voter: string }
    >;
  };

  estimateGas: {
    chairperson(overrides?: CallOverrides): Promise<BigNumber>;

    delegate(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getProposal(overrides?: CallOverrides): Promise<BigNumber>;

    getProposalLength(overrides?: CallOverrides): Promise<BigNumber>;

    getVotersList(overrides?: CallOverrides): Promise<BigNumber>;

    giveRightToVote(
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    title(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      proposal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voters(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    votersList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winnerName(overrides?: CallOverrides): Promise<BigNumber>;

    winningProposal(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    chairperson(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegate(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getProposal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProposalLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVotersList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    giveRightToVote(
      voter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    title(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vote(
      proposal: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voters(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votersList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winnerName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    winningProposal(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
