/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CodePoolInterface extends ethers.utils.Interface {
  functions: {
    "getBallotCode(bytes32[],address,string)": FunctionFragment;
    "getBusCode(address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBallotCode",
    values: [BytesLike[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBusCode",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBallotCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBusCode", data: BytesLike): Result;

  events: {};
}

export class CodePool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CodePoolInterface;

  functions: {
    getBallotCode(
      proposalNames: BytesLike[],
      _chairperson: string,
      _title: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getBusCode(
      _owner: string,
      _model: string,
      overrides?: CallOverrides
    ): Promise<[string] & { code: string }>;
  };

  getBallotCode(
    proposalNames: BytesLike[],
    _chairperson: string,
    _title: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getBusCode(
    _owner: string,
    _model: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getBallotCode(
      proposalNames: BytesLike[],
      _chairperson: string,
      _title: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getBusCode(
      _owner: string,
      _model: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getBallotCode(
      proposalNames: BytesLike[],
      _chairperson: string,
      _title: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBusCode(
      _owner: string,
      _model: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBallotCode(
      proposalNames: BytesLike[],
      _chairperson: string,
      _title: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBusCode(
      _owner: string,
      _model: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
