/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ballot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ballot__factory>;
    getContractFactory(
      name: "Bus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bus__factory>;
    getContractFactory(
      name: "BusFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BusFactory__factory>;
    getContractFactory(
      name: "CodePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CodePool__factory>;
    getContractFactory(
      name: "ContractProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContractProxy__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;

    getContractAt(
      name: "Ballot",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ballot>;
    getContractAt(
      name: "Bus",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Bus>;
    getContractAt(
      name: "BusFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BusFactory>;
    getContractAt(
      name: "CodePool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CodePool>;
    getContractAt(
      name: "ContractProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContractProxy>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
