/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Bus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bus__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "SignedConsumer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignedConsumer__factory>;
    getContractFactory(
      name: "SignedConsumerTyped",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignedConsumerTyped__factory>;
    getContractFactory(
      name: "UnsignedConsumer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UnsignedConsumer__factory>;
    getContractFactory(
      name: "UnsignedConsumerTyped",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UnsignedConsumerTyped__factory>;

    getContractAt(
      name: "Bus",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Bus>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "SignedConsumer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SignedConsumer>;
    getContractAt(
      name: "SignedConsumerTyped",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SignedConsumerTyped>;
    getContractAt(
      name: "UnsignedConsumer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UnsignedConsumer>;
    getContractAt(
      name: "UnsignedConsumerTyped",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UnsignedConsumerTyped>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
