/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Bus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bus__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "LJM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LJM__factory>;
    getContractFactory(
      name: "Itoken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Itoken__factory>;
    getContractFactory(
      name: "SimpleCrowdsale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleCrowdsale__factory>;

    getContractAt(
      name: "Bus",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Bus>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "LJM",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LJM>;
    getContractAt(
      name: "Itoken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Itoken>;
    getContractAt(
      name: "SimpleCrowdsale",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleCrowdsale>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
